#spring.application.name=JournalApp
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.uri=${MONGODB_URI}
#spring.data.mongodb.auto-index-creation=true
##spring.data.mongodb.username=username   //  we don't need these as we are not using any pass for managing the db
##spring.data.mongodb.password=password
spring:
   data:
     mongodb:
       uri: ${MONGODB_URI}
       database: journaldb
       auto-index-creation: true





server:
  port: 8081
  servlet:
    context-path: /journal



